#!/bin/bash

export WANDB_MODE=offline
export SWANLAB_API_KEY="xxx" # replace with your swanlab api key

set -x

MODEL_PATH=xxx    # replace with the path to the pretrained model path, e.g., "model/Qwen/Qwen3-VL-4B"
DATA_DIR=xxx       # contains train.parquet generated by examples/data_preprocess/opd_json.py
VAL_DIR=xxx        # contains test.parquet generated by examples/data_preprocess/vstar_bench.py

python3 -m verl.trainer.main \
    config=examples/config.yaml \
    data.train_files=${DATA_DIR}/train.parquet \
    data.val_files=${VAL_DIR}/test.parquet \
    data.format_prompt=./examples/format_prompt/opd_vstar.jinja \
    data.system_prompt=./examples/system_prompt/opd_student.txt \
    data.teacher_image_key=teacher_images \
    data.return_raw_chat=true \
    data.max_prompt_length=5120 \
    data.max_response_length=256 \
    data.rollout_batch_size=32 \
    data.val_batch_size=191 \
    algorithm.use_mm_context_distillation=true \
    algorithm.only_reverse_kl_advantages=true \
    algorithm.teacher_system_prompt=./examples/system_prompt/opd_teacher.txt \
    algorithm.disable_kl=false \
    algorithm.use_kl_loss=false \
    worker.actor.model.model_path=${MODEL_PATH} \
    worker.ref.sync_with_actor=false \
    worker.actor.global_batch_size=32 \
    worker.rollout.n=1 \
    worker.rollout.tensor_parallel_size=2 \
    worker.rollout.gpu_memory_utilization=0.85 \
    worker.reward.reward_function=./examples/reward_function/vstar.py:compute_score \
    worker.val_reward.reward_function=./examples/reward_function/vstar.py:compute_score \
    worker.actor.micro_batch_size_per_device_for_experience=4 \
    trainer.total_epochs=1 \
    trainer.save_freq=40 \
    trainer.val_freq=40 \
    trainer.experiment_name=xxx \
    trainer.find_last_checkpoint=true \
    trainer.logger='["file","swanlab"]' \
    trainer.n_gpus_per_node=4


